datenlord/datenlord

async_fuse/src/channel.rs, async_fuse/src/main.rs, async_fuse/src/session.rs
Haven't use channel in multi-thread cases.
=> #10 first attempt to add the channel

async_fuse/src/fs/mod.rs, async_fuse/src/fs/node.rs, async_fuse/src/fs/util.rs, async_fuse/src/fuse_read.rs, async_fuse/src/fuse_reply.rs, async_fuse/src/fuse_request.rs, async_fuse/src/main.rs, async_fuse/src/mount.rs, async_fuse/src/session.rs
I tested this async memfs on Linux with ARM64.
The basic filesystem functionalities work, but not quiet stable yet.
I also made some fixes to async fuse.
=> async memfs and async fuse

async_fuse/src/channel.rs, async_fuse/src/fs/mod.rs, async_fuse/src/fuse_reply.rs, async_fuse/src/fuse_request.rs, async_fuse/src/main.rs, async_fuse/src/mount.rs, async_fuse/src/protocal.rs, async_fuse/src/session.rs
I fixed more bugs, I tested the memfs using vim mostly. #13
=> more async memfs bugfix

async_fuse/src/session.rs
assert max_write_size larger than max_readahead. #17
max_write_size is the max size of FUSE request, so max_write_size must be larger than max_readahead.
also on Ubuntu 20.04, max_write_size should be no less than 128K.
=> bug fix for Ubuntu 20.04

fuse_ll/Cargo.toml, fuse_ll/src/main.rs
USAGE:
fuse_ll [OPTIONS] <mountpoint>
ARGS:
<mountpoint>
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
-o <OPTIONS>...        Mount options
=> Add command line parser for fuse_ll

.github/workflows/ci.yml
Fixes #32 
almost the same as
https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
=> Setup github actions.

.github/workflows/ci.yml, Cargo.toml, async_fuse/src/fs/mod.rs, async_fuse/src/fs/node.rs, async_fuse/src/fuse_reply.rs, async_fuse/src/main.rs, async_fuse/src/session.rs, fuse_ll/src/fuse/mount.rs, fuse_ll/src/fuse/reply.rs, fuse_ll/src/fuse/session.rs, fuse_ll/src/main.rs, fuse_ll/src/memfs.rs, fuse_ll/tests/integration_test.rs, fuse_ll/tests/test_util.rs
add Cargo.toml under root dir
disable clippy
cargo build
cargo fmt
=> #39 Fix CI

docs/coding_style.md
assertion should add explanation for failure.
=> add assertion requirement to coding style

async_fuse/Cargo.toml, async_fuse/src/fuse_request.rs, async_fuse/src/session.rs
use crossbeam bounded channel as lock-free buffer pool.
=> add buffer pool to async fuse

async_fuse/src/session.rs
=> minor fix for buffer pool

async_fuse/src/channel.rs
Wrap fcntl and ioctl into smol::blocking! macro, so
that smol runtime can schedule them out when calling.
=> #15 make Channel new real async

async_fuse/Cargo.toml, async_fuse/src/aligned_bytes.rs, async_fuse/src/byte_slice.rs, async_fuse/src/fuse_reply.rs, async_fuse/src/fuse_request.rs, async_fuse/src/main.rs, async_fuse/src/protocol.rs, async_fuse/src/session.rs
Fix the unsoundness of `ByteSlice` implementation.
Closes #67.
=> Fix unsoundness in ByteSlice

.github/workflows/audit.yml
See <https://github.com/actions-rs/audit-check#scheduled-audit>
=> Add scheduled audit

common/src/etcd_delegate.rs, csi/src/main.rs, csi/src/meta_data.rs, csi/src/util.rs
=> Remove RunAsRole::Both

Dockerfile, scripts/datenlord-entrypoint.sh, scripts/datenlord.yaml
command line arguments can be provided by datenlord.yaml
=> Add entrypoint script

csi/src/meta_data.rs
Select node from preferred topology and check in requiste topology.
=> Fix csi select node logic.

.github/workflows/cron.yml, scripts/datenlord.yaml
Reduce etcd replica to 1.
Remove e2e parallel test.
=> Increase cron stability

src/async_fuse/memfs/metadata.rs, src/async_fuse/memfs/node.rs, src/async_fuse/memfs/s3_metadata.rs, src/async_fuse/memfs/s3_node.rs
Get one lock and do all things before drop.
=> Fix several thread-safe issues.

.github/workflows/cron.yml, scripts/datenlord_perf_test.sh, scripts/fio_perf_test.sh
Add more test cases and generate result graphs.
=> Enhance datenlord fio perf test.

src/main.rs
=> Print usage when no subcommand is provided

src/async_fuse/memfs/cache/mod.rs, src/async_fuse/memfs/metadata.rs, src/async_fuse/memfs/node.rs, src/async_fuse/memfs/s3_metadata.rs, src/async_fuse/memfs/s3_node.rs
Asynchronous encapsulation of the synchronous blocking function in the cache module.
Signed-off-by: uran0sH <huangwenyuu@outlook.com>
=> Replace block_on with async

.github/scripts/install_cov_deps.sh, .github/workflows/coverage.yml, README.md, scripts/coverage.sh
=> Codecov support.

before_commit.sh, src/async_fuse/memfs/kv_engine.rs, src/async_fuse/memfs/kv_engine/mod.rs, src/async_fuse/memfs/mod.rs, src/async_fuse/memfs/serial.rs, src/common/error.rs
In order to ensure the fault tolerance and consistency of metadata, we plan to use distributed K/V engine to reconstruct metadata.
=> Refactor : Manage metadata using a distributed K/V engine

src/async_fuse/fuse/channel.rs, src/async_fuse/fuse/session.rs, src/async_fuse/memfs/mod.rs, src/async_fuse/mod.rs, src/async_fuse/test/test_util.rs
The detail problem and design are at here:
https://github.com/datenlord/datenlord/issues/364
=> Remove dyn in session, change session to be with generic type

src/async_fuse/memfs/s3_metadata.rs
If we init after exist , we will create a new default root node and replace the old one. The system will in a wrong status.
In this pull request, before we init the system, we will check if the root node exists.
- If the root node exists, we will skip the init process.
- If the root node does not exist, we will create a new root node, and use transaction to guarantee the atomicity.
=> feat(fs) : create root node with txn

src/async_fuse/memfs/cache/block.rs, src/async_fuse/memfs/cache/memory_cache.rs, src/async_fuse/memfs/cache/mock.rs, src/async_fuse/memfs/cache/mod.rs, src/async_fuse/memfs/cache/policy/lru.rs, src/async_fuse/memfs/cache/policy/mod.rs, src/async_fuse/memfs/cache/storage.rs, src/async_fuse/memfs/cache/storage_manager.rs
`StorageManager` and `InMemoryCache` are implemented in this PR, they are moved from #431.
=> feat: Implement the `StorageManager` and `InMemoryCache`

Cargo.toml, src/csi/util.rs
Removed the usage of lazy_static and replaced it with once_cell::Lazy
closes #475
=> fix: Remove lazy_static

scripts/setup/config.sh, scripts/setup/start_local_node.sh
Modify hard code command line in `start_local_node.sh`.
Reference issues: https://github.com/datenlord/datenlord/issues/487
=> fix: update start_local_node shell command line

src/storage/backend/backend_impl.rs
Try to check if the `Reader::read` has reached `0`.
Reference issue: https://github.com/datenlord/datenlord/issues/482
=> fix: check returning read size

Cargo.toml, src/async_fuse/test/test_util.rs, src/config/config.rs, src/config/inner.rs, src/main.rs, src/new_storage/backend/backend_impl.rs, src/new_storage/backend/memory_backend.rs, src/new_storage/backend/mod.rs, src/new_storage/error.rs, src/new_storage/mod.rs, src/new_storage/policy/lru.rs, src/new_storage/policy/mod.rs
In this PR, we introduced `EvictPolicy` and `Backend` for new storage, designed by @xiaguan.
Besides, we added some config items for it.
=> feat: Introduce `EvictPolicy` and `Backend` for new storage

Cargo.toml, src/new_storage/block.rs, src/new_storage/block_slice.rs, src/new_storage/memory_cache.rs, src/new_storage/mod.rs
In this PR, we introduced `Block`, `BlockSlice` and `MemoryCache` for the new storage.
=> feat: Introduce `Block`, `BlockSlice` and `MemoryCache`

Cargo.toml, src/async_fuse/memfs/s3_metadata.rs, src/new_storage/backend/backend_impl.rs, src/new_storage/block.rs, src/new_storage/block_slice.rs, src/new_storage/handle/handle.rs, src/new_storage/handle/mod.rs, src/new_storage/handle/reader.rs, src/new_storage/handle/writer.rs, src/new_storage/memory_cache.rs, src/new_storage/mod.rs, src/new_storage/storage_manager/manager.rs, src/new_storage/storage_manager/mod.rs, src/new_storage/storage_manager/tests.rs, src/new_storage/storage_trait.rs, src/new_storage/utils.rs
In this PR, we introduced `FileHandle` and `StorageManager`, the main struct in new storage.
=> feat: Introduce `FileHandle` and `StorageManager`

scripts/setup/config.sh, scripts/setup/setup_minio.sh, scripts/setup/start_local_node_with_s3.sh
Support minio as s3 backend, and use `start_local_node_s3` to create a node.
=> feat: support local s3 script.

src/async_fuse/fuse/fuse_reply.rs, src/async_fuse/fuse/session.rs, src/async_fuse/memfs/metadata.rs, src/async_fuse/memfs/mod.rs, src/async_fuse/memfs/node.rs, src/async_fuse/memfs/s3_metadata.rs, src/async_fuse/memfs/s3_node.rs, src/async_fuse/mod.rs, src/async_fuse/test/test_util.rs, src/new_storage/backend/backend_impl.rs, src/new_storage/backend/memory_backend.rs, src/new_storage/backend/mod.rs, src/new_storage/block.rs, src/new_storage/error.rs, src/new_storage/handle/handle.rs, src/new_storage/handle/reader.rs, src/new_storage/handle/writer.rs, src/new_storage/memory_cache.rs, src/new_storage/mod.rs, src/new_storage/storage_manager/manager.rs, src/new_storage/storage_manager/tests.rs, src/new_storage/storage_trait.rs
Since this PR, we will handle all storage requests with the new storage.
=> refactor: Apply new storage

.github/workflows/coverage.yml, src/cache_node/backend.rs, src/cache_node/block.rs, src/cache_node/manager.rs, src/cache_node/mod.rs, src/cache_node/policy.rs, src/cache_node/snowflake.rs, src/lib.rs
A cluster topology mechanism has been established, utilizing a HashRing for node mapping and load balancing. To promptly respond to client RPC requests when requests hit a specific node, it is essential to hold hot data in memory to minimize I/O latency.
A Cache Manager on the cache node manages memory usage and receives file flush requests. During data eviction, concurrency issues are temporarily ignored. It is assumed that each cache node has sufficient memory, and there is no current plan to incorporate multi-tier caching for expanded storage at the node level. The in-memory cache also maintains a block cache from the disk to facilitate file reading and writing.
Only block-level read and write operations are considered, and it is suggested to avoid dispersing block read-write …
=> feat(cache node): add cache node step1.

src/cache_node/snowflake.rs
Current snowflake method use sync std sleep to generate next id, update it to async one.
=> fix: update std sleep to tokio.

src/async_fuse/memfs/fs_util.rs, src/async_fuse/memfs/s3_metadata.rs
This pr implements convert_to_fuse_attr as a From trait as stated in #499.
=> refactor: implement convert_to_fuse_attr as a From trait
