- async_fuse/Cargo.toml
- async_fuse/src/fs/mod.rs
- async_fuse/src/fs/node.rs
- async_fuse/src/fs/util.rs
- async_fuse/src/fuse_request.rs
- async_fuse/src/main.rs
- async_fuse/src/mount.rs
- async_fuse/src/session.rs
- async_fuse/src/test/integration_tests.rs
- async_fuse/src/test/test_util.rs
added integration tests for async fuse.
since async fuse is a binary crate, so the integration tests have to be under src directory.
cargo clippy won't check test code.
#56
> async fuse integration tests

- async_fuse/src/fs/node.rs
- async_fuse/src/fuse_read.rs
- async_fuse/src/fuse_reply.rs
- fuse_ll/Cargo.toml
- fuse_ll/src/fuse/abi.rs
- fuse_ll/src/fuse/mod.rs
- fuse_ll/src/fuse/reply.rs
introduce bincode to fix ptrtransform warning.
ignore all unused code.
Note: We need to implement our serialize lib to simplify
byte level write and read.
> #48 fix clippy 2

- async_fuse/src/fs/dir.rs
- async_fuse/src/fs/node.rs
- async_fuse/src/fs/util.rs
- async_fuse/src/fuse_reply.rs
- async_fuse/src/main.rs
there are many lint warnings are allowed by default, so deny these allowed lint warnings.
some lint warnings need to fixed before deny them.
add some more issue to track them.
> deny some lint warnings which are allowed by default

- async_fuse/src/fs/util.rs
PR #74 is passed on GitHub action, but it's failed on ARM64. Maybe we need GitHub action on ARM64 as well.
```
error: trivial numeric cast: `u32` as `u32`
--> async_fuse/src/fs/util.rs:148:16
|
148 |         nlink: st.st_nlink as u32,
|                ^^^^^^^^^^^^^^^^^^
|
note: the lint level is defined here
--> async_fuse/src/main.rs:13:5
|
13  |     trivial_numeric_casts,
|     ^^^^^^^^^^^^^^^^^^^^^
= help: cast can be replaced by coercion; this might require a temporary variable
error: aborting due to previous error
```
> fix trivial_numeric_casts on ARM64

- async_fuse/src/fuse_request.rs
- async_fuse/src/protocol.rs
Ignore unused codes.
Skip to fix too many arguments.
> Clippy Fix 4

- fuse_ll/src/fuse/mod.rs
- fuse_ll/src/fuse/mount.rs
Use hashmap to store mount options to reduce search to O(1)
> #96 Improve command line parser performance.

- async_fuse/Cargo.toml
- fuse_ll/Cargo.toml
This is the Rust version of the [K8S host path CSI](https://github.com/kubernetes-csi/csi-driver-host-path) demo.
> add meta data to cargo.toml

- .github/workflows/ci.yml
- .travis.yml
- scripts/test.sh
This pr adds 6 checks:
|arch|os|rust|
|-|-|-|
|AMD64|ubuntu 16.04|msrv|
|Arm64|ubuntu 16.04|msrv|
|AMD64|ubuntu 16.04|stable|
|Arm64|ubuntu 16.04|stable|
|AMD64|ubuntu 16.04|nightly|
|Arm64|ubuntu 16.04|nightly|
Build status:
<https://travis-ci.com/github/datenlord/datenlord>
References:
1. <https://docs.travis-ci.com/user/languages/rust/>
2. <https://docs.travis-ci.com/user/reference/linux/>
3. <https://docs.travis-ci.com/user/reference/osx/>
> Enable travis-ci

- .github/workflows/ci.yml
According to
https://github.com/actions/virtual-environments/issues/2250,
running `apt update` before installing any software.
> Fix CI error that install fio failure

- src/async_fuse/memfs/dir.rs
- src/async_fuse/memfs/dist/client.rs
- src/async_fuse/memfs/dist/mod.rs
- src/async_fuse/memfs/dist/request.rs
- src/async_fuse/memfs/dist/response.rs
- src/async_fuse/memfs/dist/server.rs
- src/async_fuse/memfs/dist/tcp.rs
- src/async_fuse/memfs/metadata.rs
- src/async_fuse/memfs/mod.rs
- src/async_fuse/memfs/node.rs
- src/async_fuse/memfs/s3_metadata.rs
- src/async_fuse/memfs/s3_node.rs
- src/async_fuse/memfs/serial.rs
- parent dir and child file node can share a same reference and have agreement on it
- parent dir contains all children‘s file attr to accelerate the process of get child's attr , and we don't need to load attr from remote because each time lookup the parent dir with attrs is already in cache.
> Changed FileAttr to shared Arc<parking_lot::RwLock<...>>

- src/async_fuse/memfs/dist/server.rs
- src/async_fuse/memfs/inode.rs
- src/async_fuse/memfs/kv_engine.rs
- src/async_fuse/memfs/mod.rs
- src/async_fuse/memfs/s3_metadata.rs
- src/async_fuse/memfs/s3_node.rs
- src/async_fuse/memfs/serial.rs
**Problem:**
The `S3Node` struct currently holds an `Arc<S3Meta<S>>`, which simplifies many operations. However, this design is not friendly for serialization and deserialization of the `S3Node`. The majority of usages of `Arc<S3Meta<S>>`  in `S3Node` involve the `etcd_client`, `node_id`, and `volume_info` data members.
**Solution:**
This pull request refactors the `S3Node` by replacing the `Arc<S3Meta<S>>` with the three aforementioned data members (`etcd_client`, `node_id`, and `volume_info`). Additionally, serialization and deserialization support for the `S3Node` has been implemented.
**Changes:**
1. Remove the `Arc<S3Meta<S>>` data member from the `S3Node` struct,add `etcd_client`, `node_id`, and `volume_info` data members to the `S3Node` struct.
2. Update the `S3Node` constructor to …
> Refactor S3Node and add serialization/deserialization support

- Cargo.toml
- src/async_fuse/fuse/fuse_reply.rs
- src/async_fuse/memfs/metadata.rs
- src/async_fuse/memfs/mod.rs
- src/async_fuse/memfs/node.rs
- src/async_fuse/memfs/s3_metadata.rs
- src/async_fuse/memfs/s3_node.rs
- src/async_fuse/util.rs
- src/common/error.rs
This pull request refactors the error handling of the DatenLord to align with the general error handling approach of the project.
Previously, the MetaData trait was returning results of type anyhow::Result, while other parts of the codebase were returning DatenLordResult, leading to an interface mismatch and increased complexity. Additionally, using anyhow::Result provided no error type information, making it difficult to discern the exact nature of the error.
We've added a new error type, InternalErr, under DatenLordError. This new error type contains the source anyhow::Error and its context Vec<String>, effectively encapsulating the original anyhow::Error.
- Refactored  functions that were returning anyhow::Result to now return DatenLordResult with the appropriate error type.
- Added …
> Refactor DatenLord Error Handling with DatenLordError

- src/async_fuse/memfs/dist/server.rs
- src/async_fuse/memfs/inode.rs
- src/async_fuse/memfs/kv_engine.rs
- src/async_fuse/memfs/mod.rs
- src/async_fuse/memfs/s3_metadata.rs
- src/async_fuse/memfs/s3_node.rs
- src/async_fuse/memfs/serial.rs
- src/async_fuse/mod.rs
- src/async_fuse/test/test_util.rs
- src/common/etcd_delegate.rs
This Pull Request introduces some utility code to facilitate future usage of kv rebuild metadata. Here are the specific changes:
* Added traversal get and set functions for metadata. These are designed to replace the two BTreeMaps previously held by metadata.
* Modified the process for deserializing directories. Now, during deserialization, we will scan through the FillAttr of its child nodes.
* Introduced an `S3NodeWrap` structure. This is intended for handling synchronization of modifications after a node is fetched remotely.
>  Introduction of Utility Code for KV Rebuild Metadata Usage

- src/async_fuse/memfs/metadata.rs
- src/async_fuse/memfs/mod.rs
- src/async_fuse/memfs/s3_metadata.rs
This pull request primarily focuses on refactoring the operations concerning `metadata` from `memfs` to `metadata` trait. The main reason behind this change is that the previous 'memfs' was directly invoking the `metadata.cache()` which would return a `BTreeMap` interface.
However, with our recent work on the distributed K/V architecture, we've refactored `metadata`, and this interface is no longer available. To accommodate this, the refactoring presented in this PR is necessary.
Here's a brief summary of the changes:
Refactored metadata related operations from memfs.
This refactoring will help ensure the effective utilization of the new distributed K/V architecture and maintain the integrity of our `metadata` operations.
Please review the changes and let me know if you have any questions …
> Refactor Metadata Operations from MemFS to Metadata

- Cargo.toml
- src/async_fuse/memfs/kv_engine.rs
- src/common/async_fuse_error.rs
- src/common/error.rs
- src/common/etcd_delegate.rs
- src/common/mod.rs
The old etcd client has a cache layer which is not needed and there's some bugs and unlmplemented features, which takes too much effort from the main project. But the mock etcd is still kept for unit test.
> Replace etcd_client mod with more robust lib

- .github/workflows/cron.yml
Github action environment has too many preload tools that we don’t need which takes too many space, after removed them, the cron test passed.
- Add some rm operation to cron.yml to get enough space for test running.
> Fix k8s test

- .github/workflows/coverage.yml
- .gitignore
- Cargo.toml
- src/async_fuse/fuse/mount.rs
- src/async_fuse/memfs/fs_util.rs
- src/async_fuse/memfs/kv_engine/mod.rs
- src/async_fuse/memfs/metadata.rs
- src/async_fuse/memfs/mod.rs
- src/async_fuse/memfs/node.rs
- src/async_fuse/memfs/s3_metadata.rs
- src/async_fuse/memfs/s3_node.rs
- src/async_fuse/test/integration_tests.rs
This pull request consists of a series of commits designed to enhance the compatibility of the entire project with the fstest test suite. The focus is on resolving issues and adding features that allow the project to pass fstest, excluding tests related to unsupported file types.
Key Changes
**Add File Permission Check**: Implemented a feature to validate file permissions across the project.
**Add default_permission Mount Option**: Incorporated the default_permission mount option globally.
**Fix Node Update Bug**: Addressed an issue where nodes were not updated after lookup.
**Set Current User as Owner During Mount**:  Set the current user as the owner when mounting any filesystem.
Issues Resolved
#400 
#397
> Improve Datenlord for fstest Compatibility

- src/async_fuse/memfs/metadata.rs
- src/async_fuse/memfs/node.rs
- src/async_fuse/memfs/s3_metadata.rs
- src/async_fuse/memfs/s3_node.rs
- src/async_fuse/memfs/s3_wrapper.rs
As we've moved the metadata system to the kv storage, the metadata related S3 interface is useless. So let's remove it.
> refactor: remove useless S3 interface wrapper

- src/async_fuse/memfs/kv_engine/mod.rs
- src/async_fuse/memfs/metadata.rs
- src/async_fuse/memfs/mod.rs
- src/async_fuse/memfs/s3_metadata.rs
- src/async_fuse/memfs/s3_node.rs
- src/common/error.rs
- src/lib.rs
- src/main.rs
This PR aims to fix a problem of excessive usage of `panic!` in `async_fuse/memfs/s3_metadata.rs`, raised by #376 .
> Fix: Remove Excessive Usage of `panic!` in memfs Metadata Files

- .github/workflows/ci-7-23.yml
- scripts/setup/start_local_node.sh
- src/async_fuse/fuse/abi_marker.rs
- src/async_fuse/fuse/fuse_request.rs
- src/async_fuse/fuse/protocol.rs
- src/async_fuse/fuse/session.rs
- src/async_fuse/memfs/kv_engine/etcd_impl.rs
- src/async_fuse/memfs/kv_engine/mod.rs
- src/async_fuse/memfs/metadata.rs
- src/async_fuse/memfs/mod.rs
- src/async_fuse/memfs/node.rs
- src/async_fuse/memfs/s3_metadata.rs
- src/async_fuse/memfs/s3_node.rs
- src/async_fuse/memfs/serial.rs
- src/async_fuse/test/integration_tests.rs
As "exchange rename" has not yet been implemented, this PR implements it.
There are 3 main proposes in this PR:
1. Remove some dead code about `full_path` from `S3Node`, `S3Metadata` and etcd. 
2. Implement "exchange rename", which can exchange 2 files (may be in different types) atomically, and write an integration test case for it.
3. Mark codes related to FUSE request `Rename2` with feature `abi-7-23`, as `Rename2` is not supported in protocol version lower than 7.23.
Besides, this PR introduces a CI workflow for protocol version 7.23.
> feat: implement exchange rename and remove some dead code

- Cargo.toml
- src/async_fuse/memfs/cache/block.rs
- src/async_fuse/memfs/cache/mock.rs
- src/async_fuse/memfs/cache/mod.rs
- src/async_fuse/memfs/cache/policy/lru.rs
- src/async_fuse/memfs/cache/policy/mod.rs
- src/async_fuse/memfs/cache/storage.rs
This PR aims at implementing `StorageManager` as a new storage managing mechanism, introducing some trait and utilities for it, and implementing the `InMemoryCache`, which is plugged into the new mechanism, as a replacement of the old `GlobalCache`.
All targets in this PR are listed below:
When #432 is merged, clippy lints should be fixed:
Because the patches are too large, thus the `InMemoryCache` and `StorageManager` have been moved to #442.
> feat: Introduce `EvictPolicy`, `Storage` and related utilities

- src/async_fuse/memfs/metadata.rs
- src/async_fuse/memfs/mod.rs
- src/async_fuse/memfs/node.rs
- src/async_fuse/memfs/s3_metadata.rs
- src/async_fuse/memfs/s3_node.rs
This pull request introduces **transactional mechanisms** to the metadata 's **read-modify-write** operations to ensure **atomicity**  and prevent race conditions. 
Over the coming days, I plan to refactor some of the longer functions.
> reafctor(metadata) : use txn to do operations

- scripts/ci/csi-e2e-test.sh
Docker Image CI has been fixed and we can push the newest image to container registry now, therefore we restored the quick start test, which is a test for pulling DatenLord image from `ghcr.io` when deploy it to k8s.
> fix: restore quick start test

- .github/workflows/ci.yml
- Cargo.toml
- scripts/ci/csi-e2e-test.sh
- scripts/perf/datenlord-perf.yaml
- scripts/setup/datenlord.yaml
- scripts/setup/start_local_node.sh
- src/async_fuse/memfs/cache/backend.rs
- src/async_fuse/memfs/cache/block.rs
- src/async_fuse/memfs/cache/memory_cache/builder.rs
- src/async_fuse/memfs/cache/memory_cache/mod.rs
- src/async_fuse/memfs/cache/memory_cache/tests.rs
- src/async_fuse/memfs/cache/memory_cache/write_back_task.rs
- src/async_fuse/memfs/cache/mod.rs
- src/async_fuse/memfs/cache/storage_manager.rs
- src/async_fuse/memfs/mod.rs
- src/async_fuse/memfs/s3_metadata.rs
- src/async_fuse/mod.rs
- src/async_fuse/test/test_util.rs
- src/config/config.rs
- src/config/inner.rs
- src/config/mod.rs
In this PR, we introduced the backend with `openDAL`, and added new items to configure the storage module.
The patches of config items are listed below:
1. Renamed one of the variant of storage type from `None` to `Fs`, and changed its member from a `S3StorageConfig` to a String representing the root of filesystem based backend.
2. Added `--storage-mem-cache-capacity`, `--storage-mem-cache-command-limit`, `--storage-mem-write-back` and `--storage-mem-cache-soft-limit` as the cocnfig of memory cache.
3. Removed `--storage-cache-capacity`, it's for the legacy `GlobalCache`, which will be removed soon.
> feat: Introduce backend and add configurable items

- scripts/setup/create-kind-cluster.sh
- scripts/setup/datenlord.yaml
- scripts/setup/start_local_node.sh
- src/async_fuse/memfs/cache/memory_cache/cache.rs
- src/async_fuse/memfs/cache/memory_cache/write_back_task.rs
- src/async_fuse/memfs/fs_util.rs
- src/async_fuse/memfs/kv_engine/value_type.rs
- src/async_fuse/memfs/metadata.rs
- src/async_fuse/memfs/mod.rs
- src/async_fuse/memfs/node.rs
- src/async_fuse/memfs/s3_metadata.rs
- src/async_fuse/memfs/s3_node.rs
- src/async_fuse/mod.rs
- src/async_fuse/test/integration_tests.rs
- src/async_fuse/test/test_util.rs
In this PR, we refactored the `S3Metadata` with new `StorageManager`, thus the old `S3Backend`, distributed cache and `GlobalCache` are deprecated.
Because of the patch size, they will not be removed in this PR, causing the decreasing coverage.
> refactor(fs): Introduce storage for fs

- src/async_fuse/memfs/s3_metadata.rs
- src/storage/backend.rs
- src/storage/error.rs
- src/storage/memory_cache/cache.rs
- src/storage/memory_cache/tests.rs
- src/storage/memory_cache/write_back_task.rs
- src/storage/mock.rs
- src/storage/mod.rs
- src/storage/storage_manager.rs
- src/storage/storage_trait.rs
In this PR, we introduced some new error types for `storage` mod, and refactored some interfaces for futher refactoring later.
> refactor: Prepare for error handling of storage

- src/storage/backend/backend_impl.rs
- src/storage/backend/test/common.rs
- src/storage/backend/test/mock.rs
- src/storage/backend/test/mod.rs
- src/storage/backend/test/pessimistic.rs
- src/storage/block.rs
- src/storage/error.rs
- src/storage/memory_cache/cache.rs
- src/storage/memory_cache/tests.rs
- src/storage/mock.rs
- src/storage/mod.rs
1. Make `WriteBackTask` into a struct instead of a single async fn.
2. Splict `storage_manager.rs` into seperated files (submodules).
3. Functions in `storage` mod returns `Error` instead of panic. 
A single exception of *3* above is `MemoryCache::send_block_to_write_back_task`: 
```rust
panic!("Command receiver in write back task is closed unexpectedly.")
```
This will be guaranteed to be unreachable soon.
> fix: handle errors in `Storage`

- .devcontainer/devcontainer.json
- rust-toolchain.toml
In this PR, we added `rust-toolchain.toml` file to make it easier to set up the develop environment.
In addition, we added a `devcontainer.json` file to help setting up a dev container for developers to quick start. (Thanks to @yunwei37 's contribution, which is shown in #418 ).
The `rustup-init.sh` script is just downloaded from <https://sh.rustup.rs>.
> chore: add `rust-toolchain.toml` and `devcontainer.json`

- Cargo.toml
- src/async_fuse/memfs/kv_engine/etcd_impl.rs
- src/async_fuse/memfs/kv_engine/mod.rs
- src/async_fuse/memfs/mod.rs
- src/async_fuse/memfs/s3_metadata.rs
- src/async_fuse/mod.rs
- src/common/logger.rs
- src/lib.rs
- src/metrics/cache.rs
- src/metrics/file_system.rs
- src/metrics/kv.rs
- src/metrics/lock.rs
- src/metrics/mod.rs
- src/metrics/server.rs
- src/metrics/storage.rs
- src/metrics/utils.rs
- src/storage/backend/backend_impl.rs
- src/storage/memory_cache/cache.rs
In this PR, we introduced `metrics` modules for DatenLord, with metrics listed below:
- `cache`
- `file_system`
- `kv`
The metrics for `Backend` are delegated to `opendal::layers::PrometheusLayer` for now.
A trait called `LossyCast` is introduced, for casting from integer types to floating types with potentially lossy precision.
Refactored `retry_txn` macro to return the retry times.
> feat: Introduce Metrics

- src/async_fuse/memfs/fs_util.rs
- src/async_fuse/memfs/metadata.rs
- src/async_fuse/memfs/mod.rs
- src/async_fuse/memfs/node.rs
- src/async_fuse/memfs/s3_metadata.rs
- src/async_fuse/memfs/s3_node.rs
- src/async_fuse/test/integration_tests.rs
- src/main.rs
In this PR, we fixed the issue #449 to enhance code readability and conciseness.
> chore: rename user_id and group_id to uid and gid.

- Cargo.toml
- src/async_fuse/fuse/session.rs
- src/async_fuse/mod.rs
- src/async_fuse/test/integration_tests.rs
- src/async_fuse/test/test_util.rs
- src/common/mod.rs
- src/common/task_manager/gc.rs
- src/common/task_manager/manager.rs
- src/common/task_manager/mod.rs
- src/common/task_manager/task.rs
- src/common/task_manager/tests.rs
- src/csi/mod.rs
- src/csi/scheduler_extender.rs
- src/main.rs
- src/metrics/server.rs
- src/storage/memory_cache/builder.rs
- src/storage/memory_cache/cache.rs
- src/storage/memory_cache/tests.rs
- src/storage/memory_cache/write_back_task.rs
- src/storage/storage_manager/test/common.rs
- src/storage/storage_manager/test/concurrency.rs
- src/storage/storage_manager/test/latency.rs
In this PR, we managed asynchronous tasks with the `TaskManager` introduced in #478.
> refactor: Manage async tasks with task manager

- src/async_fuse/fuse/file_system.rs
- src/async_fuse/fuse/fuse_reply.rs
- src/async_fuse/fuse/protocol.rs
- src/async_fuse/fuse/session.rs
- src/async_fuse/memfs/mod.rs
- src/storage/block.rs
- src/storage/storage_manager/test/concurrency.rs
In this PR, we avoided to use raw FUSE fd to interact with FUSE kernel module, by wrapping the raw fd with `std::fs::File`. And separated threads are used to receive FUSE requests, for avoiding invoking `spawn_blocking` always.
`IoVec` is deprecated, we use `std::io::IoSlice` now.
Besides, in this PR, we use `worker fd` for each FUSE request handlers, reducing potential resources race.
> feat: make FUSE device IO asynchronous

- src/common/etcd_delegate.rs
- src/storage/cache_proxy/mod.rs
- src/storage/cache_proxy/node.rs
- src/storage/cache_proxy/ring.rs
- src/storage/mod.rs
Implement a simpe consistant hash ring by `range` array, support balance and expand.
The slot struct contains `start` and `end` range, a hashed key can be mapped to a index in slot.
```rs
pub struct Slot<T> 
where T: NodeType
{
/// The start offset of the slot
start: u64,
/// The end offset of the slot
end: u64,
/// The slot data, contains mapping info
inner: T,
}
```
The `Ring` struct contains a hash method, slots, capacity(init with 1024), version(store add/remove version), this struct is not concurrent security, we need to use `Mutex` to share ring state.
```rs
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct Ring<T, S = DefaultHashBuilder>
where T: NodeType,
S: BuildHasher
{
/// The hash builder
hash_builder: S,
/// The slots
slots: Vec<Slot<T>>,
/// T to slot id mapping, …
```
> feat: init ring implement.

- .github/workflows/coverage.yml
- src/async_fuse/fuse/session.rs
- src/async_fuse/memfs/mod.rs
- src/common/logger.rs
Current debug mode will print a lot of `data` in fuse request, when we write/flush a `1G` file, it will produce over `16G` log file.
We need to skip the `req` in MemFs::write by tracing::instrument.
> fix: skip req for log.

- scripts/setup/start_local_node.sh
- src/async_fuse/proactor/v0.rs
- src/async_fuse/test/test_util.rs
- src/bin/bind_mounter.rs
- src/common/logger.rs
- src/config/config.rs
- src/config/inner.rs
- src/csi/mod.rs
- src/main.rs
We have modified the `init_logger` function, and set filter level manually from config.
log level(from tracing):
```rs
/// The "off" level.
///
/// Designates that trace instrumentation should be completely disabled.
pub const OFF: LevelFilter = LevelFilter(None);
/// The "error" level.
///
/// Designates very serious errors.
pub const ERROR: LevelFilter = LevelFilter::from_level(Level::ERROR);
/// The "warn" level.
///
/// Designates hazardous situations.
pub const WARN: LevelFilter = LevelFilter::from_level(Level::WARN);
/// The "info" level.
///
/// Designates useful information.
pub const INFO: LevelFilter = LevelFilter::from_level(Level::INFO);
/// The "debug" level.
///
/// Designates lower priority information.
pub const DEBUG: LevelFilter = LevelFilter::from_level(Level::DEBUG); …
```
> feat: use config to control log level.

- Dockerfile
Current e2e test will fail in `scripts/ci/cron-test.sh` -> `scripts/perf/datenlord-perf-test.sh`, it is caused by latest ubuntu stragety.
error log:
```bash
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
See …
```
> fix(ci): update ubuntu with 22.04 tag

- Cargo.toml
- config.toml
- src/config/config.rs
- src/config/inner.rs
- src/main.rs
This PR use `serfig` to load config from `file`, `env`, and `command line`, then build then with priority(file < env < args).
- Reference issue: https://github.com/datenlord/datenlord/issues/437
> feat: Enhance config options with toml file and env variables

- .gitignore
- src/async_fuse/mod.rs
- src/async_fuse/test/test_util.rs
- src/config/config.rs
- src/config/inner.rs
- src/storage/backend/backend_impl.rs
Current `backend_impl` spawn task without limit, it may cause rate limit issue:
https://repost.aws/questions/QU_F-UC6-fSdOYzp-gZSDTvQ/receiving-s3-503-slow-down-responses
we need to set concurrent num in write tasks.
> fix: fix aws s3 concurrency issue.

- src/async_fuse/memfs/kv_engine/etcd_impl.rs
- src/async_fuse/memfs/kv_engine/key_type.rs
- src/async_fuse/memfs/kv_engine/mod.rs
- src/async_fuse/memfs/kv_engine/value_type.rs
- src/common/error.rs
- src/common/task_manager/task.rs
- src/storage/cache_proxy/config.rs
- src/storage/cache_proxy/mod.rs
- src/storage/cache_proxy/node.rs
- src/storage/cache_proxy/ring.rs
Now there are some nodes and an etcd server, the roles of these nodes are divided into master and slave, master needs to observe the list of all nodes and then update the result of hashing. slave needs to observe whether the master on the etcd is online or not, if not then it will try to compete to become the master, i.e.
In addition, all the keys registered with etcd are with lease, you need to take the initiative to renew the lease. In addition, when the client renews the lease, the lease may be disconnected, and then the client needs to re-apply for the lease and continue to renew the lease, and these states need to be marked. 
In this PR, we try to define some node roles in cache nodes, and try to enhance current etcd client to support keepalive and campaign.
Design Doc: …
> feat(cache node): enhance etcd client for cluster manager.

- scripts/ci/datenlord-monitor-test.sh
The current v1.8.0 image version caused the k8s-e2e-test CI to fail. In this PR, we aim to update the image version to resolve the issue and ensure the CI check passes.
> fix: fix current deprecated kube_state_metrics docker image version.

- Cargo.toml
- src/common/task_manager/manager.rs
- src/common/task_manager/task.rs
- src/common/task_manager/tests.rs
- src/storage/memory_cache/write_back_task.rs
- src/storage/storage_manager/test/latency.rs
Currently mem cache and mem storage encounter write backend failures during concurrency testing unit tests, i.e., when managing **write_back_one_block** here, the sender and receiver are affected by the global TASK_MANAGER, and there's no way to receive the task properly, causing the Brushing the backend (mem storage) fails, which is **inconsistent** with the expected behavior.
The problem occurs when it is blocked or a send error occurs, resulting in a failure to write to the backend. ~~The temporary modification here is to cancel the task that submits the block flush to ensure that the test point can pass.~~
Current block flush task failed in ut and cause inconsistent behavior in cargo test, reference issue is #531.
Because we want to use singleton task manager, this manager will create …
> fix: current block flush task failed in ut and cause inconsistent behavior in cargo test

- Cargo.toml
- src/storage/cache/mod.rs
- src/storage/cache/rpc/client.rs
- src/storage/cache/rpc/common.rs
- src/storage/cache/rpc/error.rs
- src/storage/cache/rpc/message.rs
- src/storage/cache/rpc/mod.rs
- src/storage/cache/rpc/packet.rs
- src/storage/cache/rpc/server.rs
- src/storage/cache/rpc/utils.rs
- src/storage/cache/rpc/workerpool.rs
- src/storage/cache/tests/mod.rs
- src/storage/cache/tests/rpc.rs
- src/storage/mod.rs
In response to the need for efficient file transfers in distributed environments, this system aims to achieve fast transfer of file blocks and file ranges through asynchronous RPC (ARPC) methods. The system will focus on the transfer of file blocks (block) or file ranges (range) to optimize data flow processing and ensure data consistency and efficient transfer. It is mainly used for IO-intensive data streams and is particularly suitable for block and file storage IO operations. The design goal is to minimize CPU usage and maximize throughput.
1. client connection is high, client will usually request to download bulk blocks from cache node, different blocks may be mapped to different cache node nodes, so a client may need to maintain many connections. 2. possible continuous block …
> feat(cache node): support file async rpc.

- Cargo.toml
- src/async_fuse/memfs/kv_engine/etcd_impl.rs
- src/async_fuse/memfs/kv_engine/key_type.rs
- src/storage/cache_proxy/cluster_manager.rs
- src/storage/cache_proxy/mod.rs
- src/storage/cache_proxy/node.rs
- src/storage/cache_proxy/ring.rs
In this PR, we have implemented the cluster manager for distribute cache nodes, typically for these cases:
- Election Testing: Ensure that exactly one node is elected as the control node.
- Node Addition Testing: The controller should detect new nodes and modify the hash ring accordingly.
- Offline Logic Testing: Implement testing for node disconnections, e.g., by aborting coroutines, allowing etcd to detect these changes.
- Detection and Synchronization: Other nodes should detect changes in the etcd's hash ring and synchronize their in-memory state accordingly.
The core struct is `ClusterManager` & `ClusterManagerInner`.
```rs
pub struct ClusterManager {
/// inner struct
inner: Arc<ClusterManagerInner>,
}
impl ClusterManager {
/// Create new cluster manager
pub fn new(kv_engine: …
```
> feat(cache node): support cluster manager.

- src/async_fuse/memfs/fs_util.rs
- src/async_fuse/memfs/metadata.rs
- src/async_fuse/memfs/mod.rs
- src/async_fuse/memfs/s3_metadata.rs
- src/async_fuse/memfs/serial.rs
- src/new_storage/backend/backend_impl.rs
- src/new_storage/backend/memory_backend.rs
- src/new_storage/backend/mod.rs
- src/new_storage/block.rs
- src/new_storage/memory_cache.rs
- src/new_storage/storage_manager/handle.rs
- src/new_storage/storage_manager/manager.rs
- src/new_storage/storage_manager/tests.rs
- src/new_storage/storage_trait.rs
The current file handling mechanism aggressively removes cache, but we want to retain this cache when continuous read/write operations are occurring.
Update the cache with a versioning system. The LRU (Least Recently Used) policy will automatically clean up outdated cache entries when memory is insufficient.
Additionally, we can add a `file_version` to each block to quickly identify and discard outdated blocks in access function. The current implementation does not utilize this approach.
1. Set version to cache value, write task can access outdate block and write this cache.
2. write 256k & write 4k mechaism for block version and block cache.
benchmark:
1. old policy:
```bash
python3 test_reader.py -n 10
Average read time: 0.21317 s
Maximum read time: 0.24317 s
Minimum read time: 0.18317 …
```
> feat: introduce version to storage and update cache behavior.

- Cargo.lock
- Cargo.toml
- src/distribute_kv_cache/local_cache/backend.rs
- src/distribute_kv_cache/local_cache/block.rs
- src/distribute_kv_cache/local_cache/manager.rs
- src/distribute_kv_cache/local_cache/mod.rs
- src/distribute_kv_cache/local_cache/policy.rs
- src/distribute_kv_cache/mod.rs
- src/lib.rs
Implement `Backend` trait and `FSBackend` struct for filesystem-based storage
- Added `Backend` trait with `read`, `store`, and `remove` methods.
- Implemented `FSBackend` struct using `opendal::services::Fs` for filesystem operations.
- Added tests to verify `FSBackend` functionality with basic storage operations.
> feat: introduce local cache for KVCache manager.
